const btn = document.getElementById('theme');
const saved = localStorage.getItem('hasulam-theme');
if (saved === 'light') document.body.classList.add('light');

function syncTheme() {
  btn.textContent = document.body.classList.contains('light') ? '☀' : '☾';
}

syncTheme();
btn.addEventListener('click', () => {
  document.body.classList.toggle('light');
  localStorage.setItem(
    'hasulam-theme',
    document.body.classList.contains('light') ? 'light' : 'dark'
  );
  syncTheme();
});

function normalizeReaderMarkup() {
  document.querySelectorAll('.lesson-body p').forEach((p) => {
    const text = p.textContent.trim();

    // Convert residual Markdown subheadings generated by the bootstrap renderer.
    if (text.startsWith('### ')) {
      const h4 = document.createElement('h4');
      h4.textContent = text.slice(4).trim();
      p.replaceWith(h4);
      return;
    }

    // Convert residual **bold** markers while preserving inline HTML such as <br>.
    if (p.innerHTML.includes('**')) {
      p.innerHTML = p.innerHTML.replace(/\*\*(.+?)\*\*/gs, '<strong>$1</strong>');
    }
  });

  // Remove accidental duplicate paragraph immediately following an identical heading.
  document.querySelectorAll('.lesson-body h3').forEach((heading) => {
    const next = heading.nextElementSibling;
    if (
      next &&
      next.tagName === 'P' &&
      next.textContent.trim() === heading.textContent.trim()
    ) {
      next.remove();
    }
  });
}

function addMadregaOneSourcePills() {
  const lesson = document.getElementById('madrega-1');
  if (!lesson) return;

  const sourceQuotes = [
    {
      text: 'מחשבת הבריאה היתה כדי להנות לנבראים.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'הוא השורש של חידוש, שפירושו יציאת יש מאין.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'כל חומר של הבריאה מראשה ועד סופה.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'טרם שנאצלו הנאצלים ונבראו הנבראים, היה אור עליון פשוט ממלא כל המציאות.',
      label: 'דברי האר״י',
      url: 'https://kabbalahmedia.info/he/sources/HujVytxA'
    },
    {
      text: 'כל חכמת הקבלה מיוסדת על ענינים רוחניים, שאינם תופסים לא מקום ולא זמן.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/events/cu/ZPAyLqOP?activeTab=transcription'
    }
  ];

  const paragraphs = [...lesson.querySelectorAll('.lesson-body p')];

  sourceQuotes.forEach((source) => {
    const p = paragraphs.find((candidate) => candidate.textContent.trim() === source.text);
    if (!p) return;

    const quote = document.createElement('blockquote');
    quote.className = 'source-quote';

    const label = document.createElement('div');
    label.className = 'quote-label';
    label.append(document.createTextNode(source.label + ' '));

    const link = document.createElement('a');
    link.className = 'source-pill';
    link.href = source.url;
    link.target = '_blank';
    link.rel = 'noopener';
    link.textContent = 'מקור ↗';
    label.append(link);

    const body = document.createElement('div');
    body.textContent = `„${source.text}”`;

    quote.append(label, body);
    p.replaceWith(quote);
  });
}

function setupLessonAccordion() {
  const entries = [...document.querySelectorAll('.lesson-entry')];
  const navLinks = [...document.querySelectorAll('.hero nav a[href^="#madrega-"]')];
  const openKey = 'hasulam-reader-open-madrega';
  const scrollKey = 'hasulam-reader-scroll-position';

  if (!entries.length) return;

  const entryById = (id) =>
    entries.find((entry) => entry.dataset.madrega === id);

  const safeRead = (key) => {
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  };

  const safeWrite = (key, value) => {
    try {
      if (value === null) localStorage.removeItem(key);
      else localStorage.setItem(key, value);
    } catch {
      // The reader remains fully usable when storage is unavailable.
    }
  };

  const closeOtherEntries = (activeEntry) => {
    entries.forEach((entry) => {
      if (entry !== activeEntry && entry.open) entry.open = false;
    });
  };

  const openEntry = (entry, { scroll = false, updateUrl = false } = {}) => {
    if (!entry) return;
    closeOtherEntries(entry);
    entry.open = true;
    safeWrite(openKey, entry.dataset.madrega);

    if (updateUrl) {
      history.replaceState(null, '', `#${entry.dataset.madrega}`);
    }

    if (scroll) {
      requestAnimationFrame(() => {
        entry.scrollIntoView({ behavior: 'smooth', block: 'start' });
      });
    }
  };

  entries.forEach((entry) => {
    entry.addEventListener('toggle', () => {
      if (entry.open) {
        closeOtherEntries(entry);
        safeWrite(openKey, entry.dataset.madrega);
        history.replaceState(null, '', `#${entry.dataset.madrega}`);
      } else if (!entries.some((candidate) => candidate.open)) {
        safeWrite(openKey, null);
        history.replaceState(null, '', `${location.pathname}${location.search}`);
      }
    });
  });

  navLinks.forEach((link) => {
    link.addEventListener('click', (event) => {
      const id = link.getAttribute('href').slice(1);
      const entry = entryById(id);
      if (!entry) return;
      event.preventDefault();
      openEntry(entry, { scroll: true, updateUrl: true });
    });
  });

  addEventListener('hashchange', () => {
    const entry = entryById(location.hash.slice(1));
    if (entry) openEntry(entry, { scroll: true });
  });

  const hashEntry = entryById(location.hash.slice(1));
  const savedEntry = entryById(safeRead(openKey));
  const initialEntry = hashEntry || savedEntry || entries[0];
  openEntry(initialEntry);

  if (hashEntry) {
    requestAnimationFrame(() => hashEntry.scrollIntoView({ block: 'start' }));
  } else if (savedEntry) {
    const savedScroll = Number(safeRead(scrollKey));
    if (Number.isFinite(savedScroll) && savedScroll > 0) {
      requestAnimationFrame(() => scrollTo({ top: savedScroll }));
    }
  }

  let scrollFramePending = false;
  addEventListener(
    'scroll',
    () => {
      if (scrollFramePending) return;
      scrollFramePending = true;
      requestAnimationFrame(() => {
        safeWrite(scrollKey, String(Math.round(scrollY)));
        scrollFramePending = false;
      });
    },
    { passive: true }
  );
}

normalizeReaderMarkup();
addMadregaOneSourcePills();
setupLessonAccordion();
