const btn = document.getElementById('theme');
const saved = localStorage.getItem('hasulam-theme');
if (saved === 'light') document.body.classList.add('light');

function syncTheme() {
  btn.textContent = document.body.classList.contains('light') ? '☀' : '☾';
}

syncTheme();
btn.addEventListener('click', () => {
  document.body.classList.toggle('light');
  localStorage.setItem(
    'hasulam-theme',
    document.body.classList.contains('light') ? 'light' : 'dark'
  );
  syncTheme();
});

function normalizeReaderMarkup() {
  document.querySelectorAll('.lesson-body p').forEach((p) => {
    const text = p.textContent.trim();

    // Convert residual Markdown subheadings generated by the bootstrap renderer.
    if (text.startsWith('### ')) {
      const h4 = document.createElement('h4');
      h4.textContent = text.slice(4).trim();
      p.replaceWith(h4);
      return;
    }

    // Convert residual **bold** markers while preserving inline HTML such as <br>.
    if (p.innerHTML.includes('**')) {
      p.innerHTML = p.innerHTML.replace(/\*\*(.+?)\*\*/gs, '<strong>$1</strong>');
    }
  });

  // Remove accidental duplicate paragraph immediately following an identical heading.
  document.querySelectorAll('.lesson-body h3').forEach((heading) => {
    const next = heading.nextElementSibling;
    if (
      next &&
      next.tagName === 'P' &&
      next.textContent.trim() === heading.textContent.trim()
    ) {
      next.remove();
    }
  });
}

function addMadregaOneSourcePills() {
  const lesson = document.getElementById('madrega-1');
  if (!lesson) return;

  const sourceQuotes = [
    {
      text: 'מחשבת הבריאה היתה כדי להנות לנבראים.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'הוא השורש של חידוש, שפירושו יציאת יש מאין.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'כל חומר של הבריאה מראשה ועד סופה.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/sources/kB3eD83I?language=he'
    },
    {
      text: 'טרם שנאצלו הנאצלים ונבראו הנבראים, היה אור עליון פשוט ממלא כל המציאות.',
      label: 'דברי האר״י',
      url: 'https://kabbalahmedia.info/he/sources/HujVytxA'
    },
    {
      text: 'כל חכמת הקבלה מיוסדת על ענינים רוחניים, שאינם תופסים לא מקום ולא זמן.',
      label: 'לשון בעל הסולם',
      url: 'https://kabbalahmedia.info/he/events/cu/ZPAyLqOP?activeTab=transcription'
    }
  ];

  const paragraphs = [...lesson.querySelectorAll('.lesson-body p')];

  sourceQuotes.forEach((source) => {
    const p = paragraphs.find((candidate) => candidate.textContent.trim() === source.text);
    if (!p) return;

    const quote = document.createElement('blockquote');
    quote.className = 'source-quote';

    const label = document.createElement('div');
    label.className = 'quote-label';
    label.append(document.createTextNode(source.label + ' '));

    const link = document.createElement('a');
    link.className = 'source-pill';
    link.href = source.url;
    link.target = '_blank';
    link.rel = 'noopener';
    link.textContent = 'מקור ↗';
    label.append(link);

    const body = document.createElement('div');
    body.textContent = `„${source.text}”`;

    quote.append(label, body);
    p.replaceWith(quote);
  });
}

normalizeReaderMarkup();
addMadregaOneSourcePills();
